---
abstract: 'Find a DBIC Results from Arguments'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  Catalyst::Model::DBIC::Schema: 0.43
  Catalyst::Runtime: 5.80025
  DBIx::Class: 0.08123
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Catalyst::ActionRole::BuildDBICResult
name: Catalyst-ActionRole-BuildDBICResult
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Controller::ActionRole: 0.15
  Catalyst::Runtime: 5.80025
  Moose: 1.10
  MooseX::Types: 0.23
  Perl6::Junction: 1.40000
  Try::Tiny: 0.06
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jjn1056/Catalyst-ActionRole-BuildDBICResult.git
version: 0.03
